version: '3'

services:
  flask-app:
    container_name: flask-app
    build: ./
    ports:
      - '5000:5000'
    links:
      - mysql-db

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3308:3306'
    volumes:
      - ./database:/var/lib/mysql